### ISSUE TITLE
component class does not release onDoubleTap callback

### ISSUE THREAD

**Issue by allanfann** [Arokip/flutter_diagram_editor#39]
in my opinion, on PC or Mac platform, most people still use DoubleClick
but currently the framework didn't provide such callback for developer to implement

**Comment by Arokip** [comment]
@allanfann Hello, sorry for my late answer. I am aware that double click is missing in the package but it has a reason. I implemented the gestures with GestureDetector and if you add click and double click for this widget in the same time then the on-click gesture is delayed by ~250ms because it's waiting if user clicks for the second time. I didn't want to have it in the project because there is a laggy feeling.

I am sure there is a different way how to manage it without the delay. If you know it, let me know!
